# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 15:51
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='\u5e7f\u544a\u540d\u79f0')),
                ('ad_image', models.ImageField(upload_to='./')),
            ],
        ),
        migrations.CreateModel(
            name='All_attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='\u540d\u79f0')),
                ('banner_image', models.ImageField(upload_to='./')),
            ],
        ),
        migrations.CreateModel(
            name='Favirate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('attr_values', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('product_thumb', models.ImageField(blank=True, null=True, upload_to='./')),
                ('product_intro', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4ea7\u54c1\u7b80\u4ecb')),
                ('product_sum_sal', models.IntegerField(default=0, verbose_name='\u603b\u9500\u91cf')),
                ('product_favorite_count', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570\u91cf')),
                ('rest_count', models.IntegerField(default=0, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('zhibao_year', models.IntegerField(default=1, verbose_name='\u8d28\u4fdd\u65f6\u95f4')),
                ('price', models.IntegerField(verbose_name='\u4ef7\u683c')),
                ('real_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u4fc3\u9500\u4ef7\u683c')),
                ('product_detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u4ea7\u54c1\u7ec6\u8282')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('parent_id', models.IntegerField(default=0, verbose_name='\u7236\u5206\u7c7bid')),
                ('category_ad_img', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u5206\u7c7b\u5e7f\u544a\u56fe\u7247')),
                ('category_app_big_icon', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='app\u5206\u7c7b\u5927\u56fe\u6807')),
                ('category_app_small_icon', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='app\u5206\u7c7b\u5c0f\u56fe\u6807')),
            ],
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to='./')),
                ('product_color', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u989c\u8272')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='\u6570\u91cf')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6635\u79f0')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5bc6\u7801')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='shopcar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Product_Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_attr',
            field=models.ManyToManyField(to='Api.All_attribute', verbose_name='\u4ea7\u54c1\u5c5e\u6027'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User'),
        ),
        migrations.AddField(
            model_name='favirate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Product'),
        ),
        migrations.AddField(
            model_name='favirate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User'),
        ),
    ]
