# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_product_attribut'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='attr',
            field=models.ManyToManyField(to='Api.Product_attribut'),
        ),
    ]
