# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 14:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20170413_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('price', models.IntegerField(verbose_name='\u4ef7\u683c')),
                ('real_price', models.IntegerField(blank=True, null=True, verbose_name='\u4fc3\u9500\u4ef7\u683c')),
                ('product_type', models.CommaSeparatedIntegerField(blank=True, max_length=100, null=True)),
                ('product_detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u4ea7\u54c1\u7ec6\u8282')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Product_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_thumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.FileField(upload_to='./')),
            ],
        ),
    ]
