# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_product_product_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=100, null=True, verbose_name='\u4ea7\u54c1\u7c7b\u578b'),
        ),
    ]
