# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20170414_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='\u540d\u79f0'),
        ),
    ]
