# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_auto_20170420_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_intro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4ea7\u54c1\u7b80\u4ecb'),
        ),
    ]
