# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_auto_20170421_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='\u6570\u91cf')),
                ('price', models.IntegerField(default=0, verbose_name='\u4ef7\u683c')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User')),
            ],
        ),
    ]
