# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_shopcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_favorite_count',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='product',
            name='rest_count',
            field=models.IntegerField(default=0, verbose_name='\u5e93\u5b58\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='product',
            name='zhibao_year',
            field=models.IntegerField(default=1, verbose_name='\u8d28\u4fdd\u65f6\u95f4'),
        ),
    ]
