# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_auto_20170427_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.FileField(upload_to='./')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_thumb',
        ),
    ]
