# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_auto_20170427_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='product',
            new_name='product_id',
        ),
    ]
