# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_auto_20170427_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='thumb',
            field=models.ImageField(upload_to='./'),
        ),
    ]
