# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_auto_20170427_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='real_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u4fc3\u9500\u4ef7\u683c'),
        ),
    ]
