# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_auto_20170427_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4ea7\u54c1\u7c7b\u578b'),
        ),
    ]
