# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_product_category_category_app_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='category_app_icon',
        ),
        migrations.AddField(
            model_name='product_category',
            name='category_app_big_icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='app\u5206\u7c7b\u5927\u56fe\u6807'),
        ),
        migrations.AddField(
            model_name='product_category',
            name='category_app_small_icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='app\u5206\u7c7b\u5c0f\u56fe\u6807'),
        ),
    ]
